### ISSUE TITLE
Problem in the Build process of the package

### ISSUE THREAD

**Issue by kappa95** [ros-industrial/abb_librws#111] opened 2020-10-27 09:22 UTC
Hi community,
I'm a newbie of ROS and i'm working on a project which involves a robot ABB Yumi  (IRB 14000) and i'm using this library: [library link](https://github.com/kth-ros-pkg/yumi). In order to control the camera i have seen that is needed the RWS library and i found this repository associated to that. So i cloned the in the src folder this package and i tried `catkin build` and `catkin_make_isolated` and i had errors like the one reported. How can i solve?
I'm using ROS Kinetic Kame with Ubuntu 16.04 Xenial.

```bash
kappa95@kappa95-VivoBook-ASUS-Laptop-X505ZA-X505ZA:~/yumi_depends_ws$ catkin build
------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/kinetic
Workspace:                   /home/kappa95/yumi_depends_ws
------------------------------------------------------------------
Build Space:        [exists] /home/kappa95/yumi_depends_ws/build
Devel Space:        [exists] /home/kappa95/yumi_depends_ws/devel
Install Space:      [unused] /home/kappa95/yumi_depends_ws/install
Log Space:          [exists] /home/kappa95/yumi_depends_ws/logs
Source Space:       [exists] /home/kappa95/yumi_depends_ws/src
DESTDIR:            [unused] None
------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------
[build] Found '27' packages in 0.0 seconds.                                    
[build] Updating package table.                                                
Starting  >>> abb_irb2400_moveit_plugins                                       
Starting  >>> abb_irb2400_support                                              
Starting  >>> abb_irb5400_support                                              
Starting  >>> abb_irb6600_support                                              
Starting  >>> abb_irb6640_support                                              
Starting  >>> abb_librws                                                       
Starting  >>> gazebo_mimic                                                     
Starting  >>> industrial_deprecated                                            
Finished  <<< abb_irb6600_support                          [ 0.2 seconds ]     
Starting  >>> industrial_msgs                                                  
Finished  <<< abb_irb6640_support                          [ 0.2 seconds ]     
Starting  >>> industrial_trajectory_filters                                    
Finished  <<< abb_irb2400_moveit_plugins                   [ 0.3 seconds ]     
Starting  >>> industrial_utils                                                 
Finished  <<< gazebo_mimic                                 [ 0.2 seconds ]     
Starting  >>> yumi_cameras                                                     
Finished  <<< abb_irb2400_support                          [ 0.2 seconds ]     
Starting  >>> yumi_description                                                 
Finished  <<< industrial_deprecated                        [ 0.1 seconds ]     
Starting  >>> yumi_moveit_demos                                                
Finished  <<< abb_irb5400_support                          [ 0.2 seconds ]     
Starting  >>> yumi_support                                                     
Finished  <<< industrial_trajectory_filters                [ 0.2 seconds ]     
Finished  <<< industrial_utils                             [ 0.2 seconds ]     
Finished  <<< yumi_cameras                                 [ 0.2 seconds ]     
Finished  <<< yumi_description                             [ 0.2 seconds ]     
Starting  >>> yumi_test_controllers                                            
Starting  >>> yumi_control                                                     
Starting  >>> yumi_moveit_config                                               
Finished  <<< yumi_moveit_demos                            [ 0.2 seconds ]     
Finished  <<< industrial_msgs                              [ 0.7 seconds ]     
Starting  >>> simple_message                                                   
Finished  <<< yumi_support                                 [ 0.2 seconds ]     
Finished  <<< yumi_control                                 [ 0.2 seconds ]     
Finished  <<< yumi_test_controllers                        [ 0.2 seconds ]     
Finished  <<< yumi_moveit_config                           [ 0.2 seconds ]     
_______________________________________________________________________________
Errors     << abb_librws:make /home/kappa95/yumi_depends_ws/logs/abb_librws/build.make.000.log
In file included from /home/kappa95/yumi_depends_ws/src/abb_librws/include/abb_librws/rws_client.h:48:0,
                 from /home/kappa95/yumi_depends_ws/src/abb_librws/src/rws_client.cpp:41:
/home/kappa95/yumi_depends_ws/src/abb_librws/include/abb_librws/rws_poco_client.h:42:38: fatal error: Poco/Net/HTTPCredentials.h: File o directory non esistente
In file included from /home/kappa95/yumi_depends_ws/src/abb_librws/src/rws_poco_client.cpp:43:0:
/home/kappa95/yumi_depends_ws/src/abb_librws/include/abb_librws/rws_poco_client.h:42:38: fatal error: Poco/Net/HTTPCredentials.h: File o directory non esistente
In file included from /home/kappa95/yumi_depends_ws/src/abb_librws/include/abb_librws/rws_client.h:48:0,
                 from /home/kappa95/yumi_depends_ws/src/abb_librws/include/abb_librws/rws_interface.h:40,
                 from /home/kappa95/yumi_depends_ws/src/abb_librws/src/rws_interface.cpp:40:
/home/kappa95/yumi_depends_ws/src/abb_librws/include/abb_librws/rws_poco_client.h:42:38: fatal error: Poco/Net/HTTPCredentials.h: File o directory non esistente
compilation terminated.
compilation terminated.
compilation terminated.
make[2]: *** [CMakeFiles/abb_librws.dir/src/rws_interface.cpp.o] Errore 1
make[2]: *** Attesa per i processi non terminati....
make[2]: *** [CMakeFiles/abb_librws.dir/src/rws_client.cpp.o] Errore 1
make[2]: *** [CMakeFiles/abb_librws.dir/src/rws_poco_client.cpp.o] Errore 1
make[1]: *** [CMakeFiles/abb_librws.dir/all] Errore 2
make: *** [all] Errore 2
cd /home/kappa95/yumi_depends_ws/build/abb_librws; catkin build --get-env abb_librws | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << abb_librws:make                              [ Exited with code 2 ]
Failed    <<< abb_librws                                   [ 1.7 seconds ]     
Abandoned <<< abb_irb2400_moveit_config                    [ Unrelated job failed ]
Abandoned <<< abb_irb6640_moveit_config                    [ Unrelated job failed ]
Abandoned <<< industrial_robot_client                      [ Unrelated job failed ]
Abandoned <<< industrial_robot_simulator                   [ Unrelated job failed ]
Abandoned <<< yumi_hw                                      [ Unrelated job failed ]
Abandoned <<< yumi_launch                                  [ Unrelated job failed ]
Finished  <<< simple_message                               [ 0.3 seconds ]     
[build] Summary: 18 of 25 packages succeeded.                                  
[build]   Ignored:   2 packages were skipped or are blacklisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: 6 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 2.1 seconds total.                                            
[build] Note: Workspace packages have changed, please re-source setup files to use them.
```

**Comment by gavanderhoorn** [comment] 2020-10-27 10:04
This looks like a duplicate of #110.

**Closed by gavanderhoorn** 2020-10-27 10:04 UTC
